### ISSUE TITLE
New PR from master to gh-pages to merge this approved content.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#121]
Merge a PR from `master` to `gh-pages` in order to implement in production of the content from the already merged PR.
https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/pull/120

We should consider to automate this step.

**Comment by jpradocueva** [comment]
After that. we need to reply to the submitter at https://helpdesk.openmobilealliance.org/browse/OPEN-7966

**Comment by gocadimic** [comment]
Resolved in PR #122.

**Comment by jpradocueva** [comment]
this Issue is superseded by issue #98
