### ISSUE TITLE
Enlarge search bar and add show entries

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#131]
Enhnace the current search bar to look similar to the one depicture below:

<img width="891" alt="image" src="https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/3258579/36e199e6-6105-4960-8fb4-9041917e0d77">

**Comment by rubystream** [comment]
This is addressed in #4223ba0a9388c9f79f3ef17190cf485c14959451

**Comment by jpradocueva** [comment]
Done!
