### ISSUE TITLE
Make new publication search 'non-case' sensitive

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#132]
The new search of publications is currently 'case' sensitive.
A search with the keyword "lwm2m" doesn't yield any results versus a search "LwM2M".

**Comment by rubystream** [comment]
This is resolved in fbec3c10b9c889887abe3f1a1565cd65029f42a8

**Comment by jpradocueva** [comment]
@rubystream. It works as expected, thanks.
