### ISSUE TITLE
Reset Filtering function

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#133]
After doing a search e.g., "LwM2M" and clearing the search box. The table doesn't reset to show all the enablers.

See video: https://www.screencast.com/t/pf0VmrHc

**Comment by rubystream** [comment]
This is resolved in fbec3c10b9c889887abe3f1a1565cd65029f42a8

**Comment by jpradocueva** [comment]
@rubystream, it works as expected. Thanks!
