### ISSUE TITLE
Location of api-enablers.json file

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#134]
Where can I find the .json file that contains all the documents, status, links, etc? 
We need to make this file available on this repo (for the control version), and also we need to define a continuous deployment mechanism to update the file in the API server after each merge.

**Comment by rubystream** [comment]
It's located here: https://github.com/rubystream/publication-api/tree/main/src/lambdas/data

**Comment by jpradocueva** [comment]
@rubystream thanks. I have moved a copy to the technical.openmobilealliance.org repository. Tomorrow, I would like to do a demo, and I need it at hand. 
Ideally, we should host the file in this repo and each time that we have a PR against the `gh-pages` we should update the one in the server.
