### ISSUE TITLE
Remove link from Objects page

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#149]
The following link is visible at the end of the Objects table.

![image](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/3258579/27aadfdc-ecfc-410b-bac6-7ef19f778591)

**Comment by rubystream** [comment]
fixed in fb96dcf1a072743d4bcc3a4d26f9ab17277ff03e.

**Comment by jpradocueva** [comment]
Problem solved, thanks.
