### ISSUE TITLE
Sort out fields

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#150]
Ideally the content on the fields should appear alphabetically or in ascending order for numbers. This facilitates searching e.g. for Company names. I don't know if that it is possible to do it without having a server.

**Comment by rubystream** [comment]
resolved in e61f893e383ad620a4b9917902da62ee0bfce65e

**Comment by jpradocueva** [comment]
Problem solved, thanks.
