### ISSUE TITLE
Search seems to be case sensitive. 

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#151]
Is it correct to have a search that is case-sensitive? Nowadays, people type quickly and ignore capital or lowercase names. 
Should we make it no-case sensitive?

**Comment by rubystream** [comment]
resolved in e61f893e383ad620a4b9917902da62ee0bfce65e

**Comment by jpradocueva** [comment]
Problem solved, thanks.
