### ISSUE TITLE
Add "ALL" option on the number of rows to display.

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#152]
We should add the option "ALL" on the drop menu to select the number of lines to see in one go.

![image](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/3258579/96caea74-3d29-40de-9528-0e9425fb0702)

**Comment by rubystream** [comment]
resolved in #153

**Comment by jpradocueva** [comment]
Problem solved, thanks.
