### ISSUE TITLE
Add "ALL" Tab to see all the content in one page as currently

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#153]
This option, should compose all the content fragmented on the other tabs into one page.

![2023-10-19_17-16-06](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/3258579/9bd3219d-d1e0-4cb9-a0b8-d56e92376ba1)

**Comment by rubystream** [comment]
add a link to switch between old and new format of the LwM2MRegistry page

**Comment by jpradocueva** [comment]
Problem solved, thanks!
