### ISSUE TITLE
Is possible to add statements at the beginning of the objects, bulk and resources tables?

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#154]
Currently, in the static pages, we can add content at the top or bottom of the table.
Is it possible to do the same with the dynamic tables?

![image](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/3258579/5408ecc6-a4fe-4d01-bf4a-79c9e0aa8efa)

**Comment by jpradocueva** [comment]
I can answer my own question. The answer is yes.
We still have these files to write the content at the bottom of the table:
[_OMNAInformation.html](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/blob/add-tab-interface-2-lwm2m-registry-page/OMNA/LwM2M/_OMNAInformation.html)
[_ObjectIDClasses.html](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/blob/add-tab-interface-2-lwm2m-registry-page/OMNA/LwM2M/_ObjectIDClasses.html)
[_ResourceIDClasses.html](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/blob/add-tab-interface-2-lwm2m-registry-page/OMNA/LwM2M/_ResourceIDClasses.html)
[reserved.xml](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/blob/add-tab-interface-2-lwm2m-registry-page/OMNA/LwM2M/reserved.xml)

**Comment by rubystream** [comment]
Dynamic Table currently has a caption that is at the bottom of the table.
We can make it configuratible to be at the top or at the bottom of the
table. In any case there will be only one table caption.

**Comment by jpradocueva** [comment]
Completed. It is possible to add content to the caption at the bottom of the table.
