### ISSUE TITLE
Which Fields are used for the search function?

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#155]
For instance, in the Objects table. Search for `Companies or Individuals` cannot find anything but it finds `OMA Labels`. Similarly happens with the Resources table, if you search for `IPSO` in the table it cannot find anything, but it `IPSO` is one of the submitters.

**Comment by rubystream** [comment]
The search now use the data form the filter columns as well.
Add missing columns to be searchable.

This improvements are added to 35cd3f21b2ef7f950dad6c66ea4e59c831d60e63 revision

**Comment by jpradocueva** [comment]
Completed.
