### ISSUE TITLE
Missing functionality when "DDFLink" and "TSLink" are set to 0

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/technical.openmobilealliance.org#163]
I forgot to apply the following display functionality:

If the DDF parameters `DDFLink` and `TSLink` are set to 0, then the corresponding link to the Object file or Technical Specifications link is not active or available to click.
This functionality is used to reserve objects that have not been uploaded yet. Or some Objects don't have associated a TS, then the link should not be active.

**Comment by jpradocueva** [comment]
The old page that lists all the objects still has the functionality. 

In Objects marked as TBD, the Object and TS links are not active to click.

![image](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/3258579/f2310afa-a3ac-4a0f-9016-3f7b18e89aac)

**Comment by rubystream** [comment]
Resolution is provided in #165 PR
