### ISSUE TITLE
Links on OMA LwM2M registry Object and Resource Registry page are not working

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/technical.openmobilealliance.org#179]
When land on https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html# and select `Object Classes,` the 'View" links in the ObjectID Classes table on the Operation column are not working.

<img width="1325" alt="Screenshot 2024-01-17 at 11 11 09" src="https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/19475071/51856cad-6b77-430a-a13c-49e39e4ea5bd">

Also, by selecting the `Resource` tab, the 'View" link doesn't work.
<img width="1232" alt="Screenshot 2024-01-17 at 11 12 42" src="https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/assets/19475071/ccc5f3b1-d6f2-4cd4-bca0-d44d4ae04e57">

**Comment by jpradocueva** [comment]
@rubystream, can we find the URL we can link with `View` that filters the dynamic table to show only the specific set of Object ranges?

**Comment by rubystream** [comment]
Yes, I will make the changes to the click on the link will do the appropriate selection in the dynamic table using the filtering capabilities.

**Comment by jpradocueva** [comment]
Excellent!

**Comment by gocadimic** [comment]
Resolved.

**Comment by jpradocueva** [comment]
@gocadimic, have these changes been deployed? It doesn´t work on my browser. Thanks.
