### ISSUE TITLE
LwM2M registry object view links don't work after merging into gh-pages

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/technical.openmobilealliance.org#202]
The problem with the "View" links at the ObjectID Classes preview seems to be resolved after rendering on the master/local; while in production, the links don't work again.

See PR #201

**Comment by rubystream** [comment]
Resolved with PR #203 and deployed to `gh-pages` with PR #204

**Comment by gocadimic** [comment]
Now it works as expected. Thanks!

**Comment by jpradocueva** [comment]
@rubystream, @gocadimic, excellent! I have checked it, and it does!

**Comment by gocadimic** [comment]
Closed as resolved.
